project:
  type: website
  output-dir: _site

website:
  title: "demonlab"
  favicon: images/demon.jpeg
  navbar:
    logo: images/demon.jpeg
    right: 
        - icon: house-fill
    left:
      - href: index.qmd
        text: Home
      - members.qmd
      - projects.qmd
      - papers.qmd
      - href: blog.qmd
        text: Blog
      - href: news.qmd
        text: News
      - takepart.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

