project:
  type: website
  output-dir: _site

website:
  title: "DeMON"
  favicon: images/logobraindev.png
  navbar:
    logo: images/logobraindev.png
    right: 
        - icon: house-fill
    left:
      - href: index.qmd
        text: Home
      - members.qmd
      - projects.qmd
      - papers.qmd
      # - href: blog.qmd
      #   text: Blog
      # - href: news.qmd
      #   text: News
      - href: takepart.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

