project:
  type: website

website:
  title: "DEMONLAB"
  navbar:
    logo: images/demon.jpeg
    right: 
        - icon: house-fill
    left:
      - href: index.qmd
        text: Home
      - members.qmd
      - projects.qmd
      - papers.qmd
      - href: blog.qmd
        text: Blog
      - takepart.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

